import {MigrationInterface, QueryRunner} from "typeorm";

export class FakeData1607841819332 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
      queryRunner.query(`
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Juniperus communis L. var. megistocarpa Fernald & H. St. John', 'Stefa Whittaker', 'Anti-Bacterial Deep Cleansing Hand', 12, 14, 127);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Spiranthes odorata (Nutt.) Lindl.', 'Chance Linch', 'COREG', 70, 75, 148);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Eurybia radula (Aiton) G.L. Nesom', 'Tara Urlin', 'DUREZOL', 47, 50, 134);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Polemonium nevadense Wherry', 'Kat Luke', 'KLAR and DANVER ANTIBACTERIAL HAND', 16, 19, 132);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Pertusaria paratuberculifera Dibben', 'Odetta Colcomb', 'Oxybutynin Chloride', 41, 43, 104);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Calylophus Spach', 'Berk La Grange', 'Diflunisal', 88, 93, 150);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Hemizonia congesta DC. ssp. leucocephala (Tanowitz) Keil', 'Kandy Yvens', 'Gallic Acid', 26, 28, 110);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Mertensia platyphylla A. Heller var. platyphylla', 'Ainslie Paolinelli', 'Levaquin', 18, 20, 126);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Stellaria media (L.) Vill. ssp. media', 'Jacinthe Soldi', 'Senna Laxative', 22, 25, 104);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Fissidens hyalinus Wilson & Hook.', 'Neill McAllan', 'SImply Beige Always color stay-on Makeup Broad Spectrum SPF 15', 14, 19, 115);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Stephanomeria thurberi A. Gray', 'Donnie Marlor', 'Aveeno Daily Moisturizing', 53, 54, 126);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Cynosurus cristatus L.', 'Terrie Kernar', 'triple antibiotic', 66, 70, 145);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Stemodia maritima L.', 'Dougy Bruty', 'Cerebroforce', 59, 62, 133);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Isoetes maritima Underw.', 'Candie Jarrad', 'Milk of Magnesia Mint', 57, 62, 117);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Jamesia americana Torr. & A. Gray var. rosea J.A. Purpus ex C.K. Schneid.', 'Lorna Tickle', 'Isopropyl Alcohol Surgical Scrub', 19, 24, 104);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Ayenia limitaris Cristobal', 'Chance Mottershead', 'OHUI Wrinkle Science wrinkle repair eye', 34, 39, 150);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Erigeron pumilus Nutt. ssp. intermedius Cronquist var. intermedius (Cronquist) Cronquist', 'Devan Troppmann', 'Carvedilol', 63, 68, 100);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Escobaria vivipara (Nutt.) Buxbaum', 'Gina Cours', 'ETHYL ALCOHOL', 20, 23, 129);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Rhododon ciliatus (Benth.) Epling', 'Barnabas Keirl', 'Adrenal and DHEA', 60, 62, 126);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Epilobium foliosum (Torr. & A. Gray) Suksd.', 'Eva Biggs', 'good sense ibuprofen cold and sinus', 41, 42, 109);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Argythamnia fasciculata (Vahl ex A. Juss.) Müll. Arg.', 'Jaclin Tarney', 'Homeopathic Sleep Formula', 100, 101, 116);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Quisqualis L.', 'Isac Dilland', 'Hydrochlorothiazide', 34, 37, 101);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Aegilops cylindrica Host', 'Darya Vousden', 'LBEL EFFET PARFAIT Spots Reducing Effect Foundation SPF 18 - OBSCURE 8A', 24, 29, 108);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Phegopteris Fée', 'Amalle Joinsey', 'Valsartan and hydrochlorothiazide', 88, 91, 136);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Bryocaulon divergens (Ach.) Karnefelt', 'Elayne Pitceathly', 'Treatment Set TS337681', 71, 74, 102);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Polytrichastrum alpinum (Hedw.) G.L. Sm.', 'Haily Ropars', 'Lyrica', 70, 75, 150);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Leymus arenarius (L.) Hochst.', 'Sergent Fewings', 'Quetiapine fumarate', 57, 62, 135);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Horkelia daucifolia (Greene) Rydb. ssp. daucifolia', 'Stearne Dukelow', 'TEMODAR', 86, 89, 132);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Dalea pinnata (J.F. Gmel.) Barneby var. pinnata', 'Adoree Rockall', 'INVEGA', 12, 13, 128);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Daphnopsis americana (Mill.) J.R. Johnst. ssp. caribaea (Griseb.) Nevl.', 'Frankie Dundon', 'Rocky Mountain Juniper', 52, 57, 104);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Lecanora pacifica Tuck.', 'Cyndy Drewitt', 'Hydroxyzine Hydrochloride', 57, 59, 116);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Allium bisceptrum S. Watson', 'Kerry Meaddowcroft', 'Actos', 89, 94, 129);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Nerine Herb.', 'Hanson Bloxham', 'Folic Acid', 77, 80, 114);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Muehlenbeckia Meisn.', 'Mandel Kleinsinger', 'Hoarse Cough', 66, 68, 111);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Persea Mill.', 'Dwight Hunnawill', 'Creamy Diaper Rash', 66, 68, 141);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Pelexia adnata (Sw.) Spreng.', 'Malvin Mumberson', 'Rodan and Fields', 82, 87, 127);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Galium album Mill.', 'Nanete Jephson', 'Vital Fluid IV Nano Gold Serum', 17, 20, 137);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Portulaca smallii P. Wilson', 'Evin Brockman', 'Ibuprofen', 15, 17, 136);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Phacelia cicutaria Greene var. cicutaria', 'Mal Mungane', 'Face and Body Sunscreen Spray', 52, 55, 104);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Asplenium unilaterale Lam.', 'Yolande Curran', 'Goodys Headache Relief Shot', 27, 30, 134);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Hackelia hispida (A. Gray) I.M. Johnst.', 'Amitie Ruzic', 'ABILIFY', 41, 46, 107);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Robinia ×ambigua Poir. (pro sp.)', 'Gradeigh Rhubottom', 'Flawless Finish Bare Perfection Makeup SPF 8 Mocha', 99, 100, 118);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Menegazzia A. Massal.', 'Melamie Greensides', 'Risperidone', 9, 14, 150);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Arthrostylidium Rupr.', 'Sheela Bartholomew', 'Sugared Pear Antibacterial Hand Sanitizer', 47, 49, 128);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Silphium asteriscus L. var. laevicaule DC.', 'Aubert MacCourt', 'Walgreens Calamine', 23, 26, 127);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Keckiella ternata (Torr. ex A. Gray) Straw', 'Eudora Fredi', 'Natural Pain Relieving Lavender Breeze', 28, 33, 145);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Senecio fremontii Torr. & A. Gray var. inexpectatus Cronquist', 'Lewie Load', 'EDEMA HP', 6, 11, 136);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Lupinus bicolor Lindl. ssp. bicolor', 'Davine Farnin', 'Keralac', 100, 105, 134);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Iris fulva Ker Gawl.', 'Ross Conneau', 'Naproxen', 13, 16, 121);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Coprosma waimeae Wawra', 'Nicolea Peerless', 'Emtriva', 51, 56, 109);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Sphaeralcea fendleri A. Gray ssp. fendleri', 'Damara Thomazet', 'LET ME CLARIFY', 15, 16, 118);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Isoetes acadiensis Kott', 'Greta Tatersale', 'Zoledronic Acid', 31, 34, 103);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Arabis macdonaldiana Eastw.', 'Davina Philipsohn', 'Pravastatin Sodium', 66, 71, 141);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Hainardia Greuter', 'Hewett Waddington', 'LBEL NATURAL FINISH MOISTURIZING FOUNDATION SPF 25', 53, 56, 123);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Broussaisia Gaudich.', 'Maritsa Sayton', 'Biological Complex', 91, 94, 103);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Cynara L.', 'Nata Boyan', 'PanOxyl', 70, 71, 111);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Cladonia cornuta (L.) Hoffm. ssp. groenlandica (E. Dahl) Ahti', 'Hubert Rainsden', 'venlafaxine', 94, 98, 133);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Rubus flagellaris Willd.', 'Darby Larderot', 'Tizanidine', 39, 40, 122);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Erigeron piperianus Cronquist', 'Ruby Pontefract', 'Relpax', 61, 63, 116);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Eragrostis tenuifolia (A. Rich.) Hochst. ex Steud.', 'Raychel Demangeon', 'GloStrips', 98, 103, 116);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Solidago deamii Fernald', 'Irwin Moyle', 'Sterile Water', 84, 89, 144);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Elymus diversiglumis Scribn. & C.R. Ball', 'Kirsten Allsep', 'IRBESARTAN', 51, 53, 102);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Erigeron salmonensis S.J. Brunsfeld & G.L. Nesom', 'Kelby Fowlds', 'Tranxene', 64, 67, 136);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Pedicularis canadensis L. ssp. fluviatilis (A. Heller) W.A. Weber', 'Hedvige Coppens', 'Trivora', 20, 24, 125);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Philonotis yezoana Besch. & Cardot', 'Riobard Buckner', 'ACT Total Care Sensitive Anticavity Tropical Mouth', 84, 89, 129);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Didymodon perobtusus Broth.', 'Alikee Scripps', 'Amlodipine besylate and benazepril hydrochloride', 86, 89, 132);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Monardella Benth.', 'Joshuah Maulden', 'Meloxicam', 28, 29, 144);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Lysimachia graminea (Greene) Hand.-Maz.', 'Putnam Casol', 'RISPERDAL', 74, 77, 100);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Bahia absinthifolia Benth. var. dealbata (A. Gray) A. Gray', 'Cortney Leetham', 'Fluoxetine', 77, 79, 114);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Sabicea cinerea Aubl.', 'Fulton Ayars', 'Taclonex Scalp', 23, 25, 133);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Astragalus misellus S. Watson var. misellus', 'Daron Scarffe', 'Diflucan', 52, 54, 119);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Liriope graminifolia (L.) Baker', 'Cynthie Derdes', 'Povidone Iodine', 7, 9, 145);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Descurainia obtusa (Greene) O.E. Schulz', 'Tomlin Puddicombe', 'SMART SENSE', 79, 82, 112);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Castilleja densiflora (Benth.) T.I. Chuang & Heckard ssp. obispoensis (D.D. Keck) T.I. Chuang & Heckard', 'Augustine Middle', 'Childrens Allergy Relief', 48, 49, 116);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Leptosiphon acicularis (Greene) Jeps.', 'Shaughn Thames', 'Pleo San Staph', 36, 38, 133);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Campylium hispidulum (Brid.) Mitt.', 'Othella Pennock', 'ALTERNARIA TENUIS', 16, 17, 145);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Ancistrachne uncinulata (R. Br.) S.T. Blake', 'Gunilla Paolazzi', 'AVALIDE', 75, 80, 127);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Caulanthus simulans Payson', 'Neall Shewen', 'Sulfamethoxazole and Trimethoprim', 97, 100, 126);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Callistemon pallidus (Bonpl.) DC.', 'Brianne Gaw', 'Listerine', 74, 76, 132);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Spiraea L.', 'Aloysius Dunkinson', 'Esterified Estrogens and Methyltestosterone', 40, 44, 148);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Nekemias arborea (L.) J. Wen & Boggan', 'Asa Miell', 'healthy accents allergy relief', 40, 43, 115);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Thelypteris boydiae (D.C. Eaton) K. Iwats.', 'Gearard Cowland', 'Kit for the Preparation of Technetium Tc99m Disofenin', 33, 37, 150);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Caloplaca obliterans (Nyl.) Blomb. & Forss.', 'Winonah Bartolic', 'Alprazolam', 7, 11, 106);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Viola sagittata Aiton', 'Oswell Scoterbosh', 'Halibut', 44, 49, 150);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Isoetes engelmannii A. Braun', 'Grazia Undy', 'Flu-less', 50, 51, 122);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Astragalus callithrix Barneby', 'Gussie Dutt', 'Ceramide Lift And Firm Makeup Broad Spectrum Sunscreen SPF 15 Buff', 66, 67, 124);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Baccharis angustifolia Michx.', 'Pembroke Storer', 'AUGMENTIN', 55, 57, 139);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Myrsine knudsenii (Rock) Hosaka', 'Basia Avrahamy', 'Ropinirole Hydrochloride', 76, 78, 144);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Cotoneaster hupehensis Rehder & E.H. Wilson', 'Gerti Kingsnod', 'Smart Sense Acid Reducer', 93, 97, 105);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Dendrophthora Eichl.', 'Jacquelin Wherrit', 'Promethazine VC', 54, 57, 100);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Solidago radula Nutt. var. radula', 'Vannie Stonman', 'Gumnumb Topical Anesthetic', 29, 33, 142);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Laelia rubescens Lindl.', 'Munroe Grimmolby', 'Bromfenac', 5, 8, 118);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Lonicera korolkowii Stapf', 'Cesare Grimston', 'Hydrochlorothiazide', 5, 8, 136);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Pteryxia terebinthina (Hook.) J.M. Coult. & Rose var. terebinthina', 'Brien Boobyer', 'Zetia', 25, 27, 134);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Purshia glandulosa Curran', 'Colman Sallier', 'Happy Happy', 69, 73, 125);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Tuckermannopsis ciliaris (Ach.) Gyel.', 'Reggis Yakushkin', 'Magnesium Citrate', 51, 54, 146);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Cacaliopsis A. Gray', 'Karon Corrett', 'Muscle Ease', 30, 35, 117);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Hygrophila polysperma (Roxb.) T. Anderson', 'Carly Norkutt', 'Crest Pro-Health', 87, 88, 150);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Tephrosia angustissima Shuttlw. ex Chapm.', 'Cherice Worsham', 'Garnier Skin Renew Dark Spot Hand Treatment Broad Spectrum SPF 30', 3, 4, 129);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Penstemon breviculus (D.D. Keck) Nisbet & R.C. Jacks.', 'Derwin Miskin', 'Pioglitazone Hydrochloride', 12, 15, 149);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Canotia Torr.', 'Gunner Haensel', 'Halobetasol Propionate', 42, 47, 146);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Tortula latifolia Bruch ex Hartm.', 'Micky Joel', 'Baclofen', 65, 70, 105);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Buellia modesta (Krempelh.) Müll. Arg.', 'Jerry Dorran', 'Prochieve', 7, 8, 101);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Timmiella (De Not.) Limpr.', 'Cyrus Hartil', 'Neomycin and Polymyxin B Sulfates and Hydrocortisone', 38, 41, 135);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Buchnera pusilla Kunth', 'Alvie Glasheen', 'Nostrilla', 71, 75, 101);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Juncus paludosus E.L. Bridges & Orzell', 'Jackelyn Persehouse', 'Hydroxyzine Hydrochloride', 56, 59, 133);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Pertusaria chiodectonoides Bagl. ex A. Massal.', 'Chaddie Knock', 'SUMATRIPTAN SUCCINATE', 29, 33, 131);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Jacquiniella teretifolia (Sw.) Britton & P. Wilson', 'Arnold Mattiassi', 'Nadolol', 94, 95, 126);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Urvillea Kunth', 'Nomi Wakley', 'Justice Vanilla ANTI BAC HAND SANITIZER', 23, 24, 114);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Schoepfia arenaria Britton', 'Stanislaus Clampe', 'DIMETHICONE and ZINC OXIDE', 10, 12, 132);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Stylisma aquatica (Walter) Raf.', 'Efren Tiebe', 'MediChoice Hand Sanitizer', 91, 92, 140);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Madia elegans D. Don ex Lindl. ssp. wheeleri (A. Gray) D.D. Keck', 'Jenny Colman', 'Treatment Set TS348335', 79, 80, 123);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Digitaria fuscescens (J. Presl) Henr.', 'Sisely Hedge', 'Leader Ibuprofen', 78, 82, 140);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Cladonia ochrochlora Flörke', 'Shanda Cammock', 'Neomycin and Polymyxin B Sulfates and Hydrocortisone', 50, 54, 120);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Sairocarpus multiflorus (Pennell) D.A. Sutton', 'Matty Clemes', 'Pigweed Mixture', 77, 81, 107);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Phemeranthus rugospermus (Holz.) Kiger', 'Dorri McAlpin', 'equaline pain relief', 38, 40, 141);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Penstemon labrosus (A. Gray) Hook. f.', 'Haze Freddi', 'Epoprostenol Sodium', 29, 33, 136);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Aglaonema pictum (Roxb.) Kunth', 'Georas Cocklin', 'AVVA', 14, 15, 107);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Hypericum boreale (Britton) E.P. Bicknell', 'Clim Orritt', 'Fluoxetine', 82, 85, 135);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Rhodobryum ontariense (Kindb.) Par.', 'Brendis Boatman', 'SuperSmile Professional', 63, 65, 100);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Mirabilis pumila (Standl.) Standl.', 'Clywd Silber', 'Divalproex Sodium', 17, 20, 126);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Aspicilia verrucigera Hue', 'Ellen Ballinger', 'Lotensin HCT', 54, 59, 114);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Ramalina scoparia Vain.', 'Astra Checchetelli', 'Ibuprofen', 96, 100, 104);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Hedysarum occidentale Greene var. occidentale', 'Nesta Woolland', 'Chest Cold', 30, 32, 105);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Rosa ×alba L. (pro sp.)', 'Marrissa Dannell', 'Neutrogena Wet Skin Swim-Humidity-Sweat Sunblock', 2, 6, 150);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Cypripedium arietinum W.T. Aiton', 'Kendell Lammerts', 'Fexofenadine Hydrochloride', 5, 9, 138);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Inula britannica L.', 'Liva Patron', 'Edex', 99, 100, 132);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Castilleja flava S. Watson var. rustica (Piper) N.H. Holmgren', 'Karen Hablet', 'Phenazopyridine Hydrochloride', 71, 73, 149);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Iris tenax Douglas ex Lindl. ssp. klamathensis Lenz', 'Chrissie Pfaff', 'Naratriptan', 48, 49, 126);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Aspicilia perradiata (Nyl.) Hue', 'Conrado Caldaro', 'SF', 40, 42, 110);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Cirsium chellyense J.W. Moore & Frankton', 'Nicolette Antonio', 'Keep the Peace', 77, 78, 144);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Rubus plus L.H. Bailey', 'Marie-jeanne Trematick', 'Mestinon', 41, 44, 145);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Armeria maritima (Mill.) Willd. ssp. maritima', 'Krista Dagwell', 'Sterile Water', 51, 54, 139);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Omphalodes aliena A. Gray', 'Ethel Conneely', 'Sunmark Arthritis 8 Hour', 13, 17, 108);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Silphium terebinthinaceum Jacq.', 'Rozella Cafferty', 'Clopidogrel', 79, 84, 150);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Arctoparmelia Hale', 'Brooks Stonhard', 'Gap Favorite Lip Balm', 82, 84, 101);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Elymus glaucus Buckley ssp. virescens (Piper) Gould', 'Garrik Drennan', 'Dextrose', 18, 20, 133);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Solidago rupestris Raf.', 'Karylin Goodlatt', 'CliniShield Instant Hand Sanitizer Fragrance Free', 41, 43, 104);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Xanthoparmelia lipochlorochroa Hale & Elix', 'Bret Dafydd', 'Silphen', 94, 96, 150);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Halesia carolina L.', 'Tilda Loram', 'Dyural LM Kit', 42, 47, 104);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Descurainia Webb & Bethel.', 'Deck Grattan', 'METOPROLOL SUCCINATE', 89, 94, 109);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Bidens sandvicensis Less. ssp. sandvicensis', 'Sonja Vazquez', 'Carvedilol', 71, 72, 132);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Ribes divaricatum Douglas var. pubiflorum Koehne', 'Lowe Sandey', 'SPF 50', 62, 67, 141);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Allionia incarnata L. var. villosa (Standl.) B.L. Turner', 'Annamaria Tommeo', 'Gentle Laxative', 93, 96, 114);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Polypogon monspeliensis (L.) Desf.', 'Madelin Groombridge', 'Mineral Wear Talc Free Airbrushing Pressed Powder', 13, 17, 114);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Cynosurus cristatus L.', 'Tobe Beatty', 'Health Mart infants pain and fever', 3, 5, 102);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Dichelachne Endl.', 'Chery Olivelli', 'ESIKA 3-IN-1 PRO MAKE UP FOUNDATION SPF 20 BASE DE MAQUILLAJE PARA ROSTRO 3-EN-1 PRO FPS 20', 93, 97, 142);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Helianthus silphioides Nutt.', 'Georgianna Spowage', 'Flu Relief', 14, 19, 148);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Ericameria nauseosa (Pall. ex Pursh) G.L. Nesom & Baird ssp. nauseosa var. latisquamea (A. Gray) G.L. Nesom & Baird', 'Garnet Lodwick', 'Solu-Medrol', 76, 77, 144);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Gymnostomiella Fleisch.', 'Mal Loadsman', 'CAREALL Artifical Tears', 61, 64, 130);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Biatorella floridensis H. Magn.', 'Ula Keppie', 'Apple Spice Antibacterial Foaming Hand Wash', 10, 14, 139);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Leptogium tenuissimum (Dicks.) Körb.', 'Valma Copestick', 'Hydralazine Hydrochloride', 59, 60, 142);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Ipomoea eggersiana Peter', 'Marylinda Porcher', 'Darby', 82, 86, 102);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Grindelia stricta DC.', 'Celka Gotch', 'Levobunolol Hydrochloride', 42, 45, 103);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Bromus erectus Huds.', 'Alistair Bunclark', 'Ativan', 25, 28, 119);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Trifolium dasyphyllum Torr. & A. Gray ssp. uintense (Rydb.) J.M. Gillett', 'Leona Clardge', 'COREG', 61, 66, 136);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Romneya trichocalyx Eastw.', 'Livvyy Leyrroyd', 'PerioMed', 20, 21, 109);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Draba globosa Payson', 'Victoir Robinet', 'Childrens Acetaminophen', 37, 42, 107);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Carex fissuricola Mack.', 'Anastasia Ovize', 'Oral Saline Laxative', 12, 13, 118);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Rorippa columbiae (Suksd. ex B.L. Rob.) Suksd. ex Howell', 'Marybeth Grancher', 'CHAPSTICK MOISTURIZER', 52, 56, 142);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Platanus wrightii S. Watson', 'Midge Gerrit', 'BHI Arthritis', 72, 77, 126);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Festuca scabra Vahl', 'Maxy Waldock', 'Pain Relief', 41, 44, 135);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Gossypianthus lanuginosus (Poir.) Moq. var. lanuginosus', 'Lorrie Whitnell', 'Pain ReliefPatches', 80, 82, 111);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Lecidea mannii Tuck.', 'Evelyn Paladini', 'Covergirl Queen Collection All Day Flawless 3in1 Foundation', 69, 73, 111);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Scoliopus Torr.', 'Bettina Leamy', 'Nitrofurantoin (monohydrate/macrocrystals)', 72, 77, 123);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Arabis repanda S. Watson', 'Erminie Thresher', 'Illuminating Daily Moisturizer', 38, 41, 144);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Oxytropis deflexa (Pall.) DC. var. sericea Torr. & A. Gray', 'Ebba Barrus', 'AgroBac Foam Wash', 72, 76, 121);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Rollinia pulchrinervis A. DC.', 'Dosi Shakeshaft', 'Nystatin', 79, 83, 145);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Symphyotrichum puniceum (L.) Á. Löve & D. Löve', 'Vyky Wickmann', 'Gongjinhyang Qi and Jin Eye', 12, 13, 130);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Euphorbia innocua L.C. Wheeler', 'Robinet Moakes', 'CALIFORNIA NATUREL ALL NATURAL SUNSCREEN', 77, 80, 120);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Aloysia gratissima (Gillies & Hook.) Troncoso var. schulziae (Standl.) L.D. Benson', 'Rudolph Lightman', 'Rye Grain', 86, 91, 118);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Oxalis alpina (Rose) Rose ex R. Knuth', 'Clotilda Manktelow', 'NAPROXEN', 40, 41, 146);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Coprosma ×molokaiensis H. St. John (pro sp.)', 'Rossie Trelease', 'Pure Finish Mineral Powder Foundation SPF 20', 28, 33, 139);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Thymophylla Lag.', 'Cary Abramson', 'Ropinirole Hydrochloride', 92, 97, 132);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Brassavola cucullata (L.) R. Br.', 'Jessamyn Shotter', 'Q Tussin DM', 18, 20, 104);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Castilleja applegatei Fernald ssp. applegatei', 'Hesther Mardy', 'PROMETHAZINE DM', 64, 68, 149);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Carex ×abitibiana Lepage', 'Waring Beel', 'HAND SANITIZING', 39, 41, 144);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Allium simillimum L.F. Hend.', 'Maurene Saylor', 'Altidome', 59, 60, 129);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Borassus aethiopum Mart.', 'Shellysheldon Videneev', 'Namenda', 95, 96, 103);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Dalea scandens (Mill.) R.T. Clausen', 'Ker Giamelli', 'Cepacol', 92, 94, 135);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Polygonum cascadense W.H. Baker', 'Edan Ferrier', 'SCRUBS Lemon Hand Sanitizer Wipes', 18, 22, 136);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Sisymbrium L.', 'Stinky Stonall', 'Chicken Feather', 56, 60, 126);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Eubotrys Nutt.', 'Ferris MacVagh', 'Super Restorative Foundation True Lift SPF 15 Tint 2.5', 16, 21, 119);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Rumex acetosella L.', 'Vasili O''Breen', 'Bloxiverz', 59, 60, 111);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Stylosanthes humilis Kunth', 'Paulie McKeaney', 'VITALUMIERE', 55, 58, 140);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Synthyris canbyi Pennell', 'Dianna Reijmers', 'Amantadine Hydrochloride', 36, 37, 119);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Pinus caribaea Morelet', 'Philippe Biddell', 'Promethazine Hydrochloride', 75, 76, 129);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Citrus jambhiri Lush.', 'Charlotta Mauchline', 'Phoslo', 10, 12, 111);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Hibiscus kokio Hillebr. ex Wawra', 'Marcello Ioannou', 'Pomegranate Hand Sanitizer', 29, 30, 134);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Arenaria pumicola Coville & Leiberg', 'Kath Tatton', 'White Birch', 50, 55, 128);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Castela erecta Turp. ssp. erecta', 'Prentiss Schwandt', 'Ibuprofen', 71, 72, 132);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Lecania A. Massal.', 'Randy Robet', 'DOXEPIN HYDROCHLORIDE', 90, 91, 130);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Teucrium canadense L. var. hypoleucum Griseb.', 'Brandon Goundrill', 'California Black Walnut', 87, 89, 132);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Usnea finkii Zahlbr.', 'Sauveur Ashall', 'night time', 38, 41, 132);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Malacothamnus davidsonii (B.L. Rob.) Greene', 'Heddi Braisher', 'Up and Up Nicotine', 13, 16, 136);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Phyllanthus distichus Hook. & Arn.', 'Melli Taffee', 'Aveeno Ultra-Calming Daily Moisturizer', 28, 32, 144);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Ceroxylon Bonpl. ex DC.', 'Roman Kee', 'Atropine Sulfate', 94, 96, 106);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Plectranthus amboinicus (Lour.) Spreng.', 'Arnuad Vlasenko', 'Lower GI Relief', 76, 81, 119);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Hirtella L.', 'Winona Bummfrey', 'berkley and jensen allergy', 34, 36, 113);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Melilotus wolgicus Poir.', 'Wald Straker', 'Bismatrol', 58, 59, 147);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Sorbus americana Marshall', 'Stanislas Gage', 'Nitroglycerin', 15, 20, 116);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Endocarpon lepidallum Nyl.', 'Bertina Draycott', 'Pravastatin Sodium', 96, 99, 121);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Solanum glaucophyllum Desf.', 'Ruthanne Heinzler', 'Hepastat', 67, 69, 113);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Erigeron piperianus Cronquist', 'Missie Willwood', 'Tandem Plus', 4, 8, 140);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Tephromela M. Choisy', 'Catharine Karlolak', 'MDSolarSciences SPF50 Plus Ultra Mineral Screen', 50, 55, 116);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Allophyllum gilioides (Benth.) A.D. Grant & V.E. Grant', 'Gino Farthing', 'Topcare Sinus Relief', 35, 38, 120);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Alternanthera caracasana Kunth', 'Corny Eblein', 'LiveBetter', 75, 76, 139);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Botrychium lanceolatum (S.G. Gmel.) Angstr. var. angustisegmentum Pease & A.H. Moore', 'Sapphire Minards', 'Cold', 10, 15, 109);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Paraserianthes lophantha (Willd.) I.C. Nielsen', 'Bernadine McKinnon', 'Famotidine', 87, 90, 142);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Senna bacillaris (L. f.) Irwin & Barneby', 'Joleen Feldharker', 'no zit sherlock acne', 31, 34, 130);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Rubus caesius L.', 'Dieter Disney', 'Pulmo Ferrum', 78, 81, 104);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Malpighia linearis Jacq.', 'Cecil Phelit', 'Lidocaine Hydrochloride', 86, 91, 138);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Bulbophyllum Thouars', 'Arleen Lamey', 'GEODON', 58, 62, 102);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Penstemon anguineus Eastw.', 'Liliane Bollini', 'UREA', 1, 5, 140);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Ambrosia trifida L.', 'Nikolai Blakeway', 'Equaline Naproxen Sodium', 22, 25, 114);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Clematis versicolor Small ex Rydb.', 'Roberta Haspineall', 'Lunesta', 90, 92, 141);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Baptisia arachnifera Duncan', 'Beatrice Hurler', 'FRAXINUS AMERICANA POLLEN', 5, 9, 124);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Dicranum latifolium Amann', 'Eleonore Gasking', 'Ampicillin', 77, 81, 148);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Fissidens pauperculus Howe', 'Nanice Chilcott', 'Vinorelbine', 59, 60, 128);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Clarkia gracilis (Piper) A. Nelson & J.F. Macbr.', 'Gerrilee Jeakins', 'Oi Lin Natural Sunscreen SPF 30', 5, 6, 144);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Hydrophyllum virginianum L. var. atranthum (Alexander) Constance', 'Alicea Cotterill', 'Minocin', 70, 75, 107);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Cyrtandra ×laevis H. St. John (pro sp.)', 'Bobbe Youell', 'Diazepam', 36, 37, 118);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Lobelia yuccoides Hillebr.', 'Sayer Newdick', 'Olive Pollen', 19, 20, 107);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Marsilea minuta L.', 'Hailee Havoc', 'Vancomycin Hydrochloride', 95, 97, 134);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Acarospora peltastica Zahlbr.', 'Cam Jales', 'Renewal Anti-Wrinkle', 10, 13, 105);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Graphina scolectis (Tuck.) Fink', 'Kory Moxom', 'Alprazolam', 12, 14, 107);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Asplenium palmeri Maxon', 'Ottilie Doyland', 'SPRYCEL', 53, 57, 137);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Citrullus colocynthis (L.) Schrad.', 'Averil Codeman', 'Berry Scented Hand Sanitizer', 39, 40, 114);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Geum geniculatum Michx.', 'Stanwood Lisle', 'Ziprasidone', 86, 90, 139);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Cassytha filiformis L.', 'Rachele Ainslee', 'Valacyclovir Hydrochloride', 45, 49, 135);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Carlowrightia linearifolia (Torr.) A. Gray', 'Lonni Moukes', 'Niaspan', 30, 31, 134);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Sabatia brachiata Elliott', 'Bev Piggen', 'Truvada', 69, 73, 113);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Juncus vaseyi Engelm.', 'Tanitansy Laughton', 'CENTER-AL - PLANTAGO LANCEOLATA POLLEN', 19, 21, 137);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Triteleia ixioides (W.T. Aiton) Greene ssp. cookii (Hoover) Lenz', 'Riane Abrahamsohn', 'Dilantin', 37, 39, 104);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Elaphoglossum petiolatum (Sw.) Urb.', 'Allsun Snasel', 'Kadian', 28, 30, 119);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Anoectochilus sandvicensis Lindl.', 'Jobye McVey', 'Chlorthalidone', 88, 89, 143);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Penstemon hirsutus (L.) Willd.', 'Donal Pancast', 'Amoxicillin and Clavulanate Potassium', 1, 2, 132);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Indusiella thianschanica Broth. & Müll. Hal.', 'Amelita Katt', 'Lamotrigine', 77, 82, 100);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Rhinanthus minor L. ssp. groenlandicus (Ostenf.) L. Neum.', 'Janenna Hopkynson', 'NADH Plus', 80, 85, 128);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Encalypta intermedia Jur.', 'Sara Duiged', 'Sensorcaine', 65, 70, 121);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Oligoneuron ×krotkovii (B. Boivin) G.L. Nesom', 'Viki Bonifas', 'Severe Cold Relief', 45, 46, 115);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Spergularia echinosperma (Celak.) Asch. & Graebn.', 'Philippe Cuschieri', 'Ciprofloxacin', 50, 54, 149);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Listera auriculata Wiegand', 'Thorin Stabler', 'Lung Detox', 81, 84, 132);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Iwatsukiella W.R. Buck & H.A. Crum', 'Torry Bakhrushkin', 'Cystoforce', 6, 11, 113);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Artemisia bigelovii A. Gray', 'Ester Pattingson', 'EXTENDED PHENYTOIN SODIUM', 42, 47, 121);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Buchnera obliqua Benth.', 'Reece Shayes', 'Conray 43', 53, 56, 138);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Cryptantha minima Rydb.', 'Catie Leidl', 'Melvita PROSUN SPF 30 Sun', 30, 32, 140);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Sidalcea malviflora (DC.) A. Gray ex Benth. ssp. laciniata C.L. Hitchc. var. laciniata', 'Reynold Nisot', 'Aspirin', 26, 28, 149);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Cochlidium serrulatum (Sw.) Bishop', 'Glynis Churcher', 'Cultivated Oat', 96, 101, 123);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Ranunculus flammula L. var. filiformis (Michx.) Hook.', 'Lisle Pantridge', 'Metformin Hydrochloride', 19, 21, 101);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Mitella stauropetala Piper var. stenopetala (Piper) Rosend.', 'Lefty Ney', 'CC Cream Light', 90, 91, 146);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Dryopteris ×correllii W.H. Wagner', 'Lea Volkers', 'Good Sense Nicotine', 24, 27, 105);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Polygala intermontana T. Wendt', 'Coralyn Robbel', 'laxative', 52, 55, 127);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Placynthiella hyporhoda (Th. Fr.) Coppins & P. James', 'Lurline Swaffield', 'Isosorbide Mononitrate', 99, 102, 106);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Wikstroemia oahuensis (A. Gray) Rock var. palustris (Hochr.) Peterson', 'Amelina O''Doherty', 'Healing Waters White Tea Pear Hand Sanitizer', 93, 96, 116);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Eucalyptus behriana F. Muell.', 'Erich Penwell', 'Bupropion Hydrochloride', 70, 72, 134);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Rondeletia L.', 'Spike Petrashkov', 'Sure Conditioning Solid Vitamin Infusion', 47, 52, 122);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Polygala smallii R.R. Sm. & Ward', 'Maurice Heiss', 'risperidone', 14, 15, 142);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Eriogonum heermannii Durand & Hilg. var. sulcatum (S. Watson) Munz & Reveal', 'Seamus Wealleans', 'Wal Itin', 2, 6, 110);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Clematis socialis Kral', 'Nerta D''Abbot-Doyle', 'Synalgos', 14, 18, 137);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Eutrema edwardsii R. Br.', 'Derek Pollastro', 'Brut Blue Wave', 65, 67, 117);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Areca L.', 'Brooks Rispin', 'ecolyptus pain relieving muscle rub', 11, 12, 145);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Trifolium incarnatum L.', 'Kristian O''Farrell', 'Levetiracetam', 51, 55, 131);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Micarea prasina Fr.', 'Sammy Struther', 'Cyclobenzaprine Hydrochloride', 19, 23, 118);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Embelia pacifica Hillebr.', 'Early Ashment', 'dg health ibuprofen', 74, 78, 141);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Lesquerella parvula Greene', 'Daisey Brittain', 'DOCUSATE SODIUM 100mg Two-Tone', 32, 35, 134);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Phacelia suaveolens Greene ssp. suaveolens', 'Dell Bowker', 'Isuprel', 6, 9, 103);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Rhynchospora fascicularis (Michx.) Vahl var. distans (Michx.) Chapm.', 'Hillard Glisenan', 'Flaxseed', 10, 11, 134);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Isoetes valida (Engelm.) Clute', 'Amalita Carolan', 'Profilnine', 67, 68, 138);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Salvia hierosolymitana Boiss.', 'Anabel Jaggar', 'Niravam', 18, 23, 109);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Peperomia membranacea Hook. & Arn.', 'Adair Uden', 'Topiclear Xtra beauty', 12, 15, 109);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Samolus ebracteatus Kunth', 'Oralee Kynd', 'Hectorol', 86, 88, 120);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Barbula ehrenbergii (Lor.) Fleisch.', 'Franky Sargeaunt', 'donepezil hydrochloride', 12, 15, 137);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Camissonia brevipes (A. Gray) P.H. Raven ssp. arizonica (P.H. Raven) P.H. Raven', 'Foss Kem', 'Firebush/Burning Bush', 32, 33, 131);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Crepis atribarba A. Heller ssp. originalis (Babc. & Stebbins) Babc. & Stebbins', 'Liane Hughesdon', 'Hydrocodone Bitartrate and Acetaminophen', 9, 10, 140);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Trichosanthes cucumerina L.', 'Nerte Huey', 'Ibuprofen and Pseudoephedrine Hydrochloride', 73, 74, 114);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Arthonia byssacea (Weigel) Almq.', 'Gunilla Wines', 'Clorazepate Dipotassium', 67, 72, 104);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Bebbia juncea (Benth.) Greene', 'Cinnamon Burcher', 'Myzilra', 12, 16, 124);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Eustoma exaltatum (L.) Salisb. ex G. Don', 'Arvie Tarburn', 'Treatment Set TS330376', 59, 60, 139);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Penstemon tubaeflorus Nutt.', 'Hadria Cattrell', 'Treatment Set TS350094', 94, 95, 120);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Sidalcea oregana (Nutt. ex Torr. & A. Gray) A. Gray ssp. hydrophila (A. Heller) C.L. Hitchc.', 'Ulrika Simonnin', 'Herbion Naturals', 69, 72, 116);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Hymenoclea salsola Torr. & A. Gray var. pentalepis (Rydb.) L.D. Benson', 'Mitzi Ropkes', 'Sarna', 42, 43, 149);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Lepidium montanum Nutt. var. tenellum (L.O. Williams) C.L. Hitchc.', 'Godfree Williment', 'SUPER AQUA MAX DEEP MOISTURE SLEEPING PACK', 44, 46, 133);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Hibiscadelphus stellatus H. Oppenh., Bustamente & Perlman', 'Karalee Laxon', 'Fluconazole', 98, 101, 133);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Venturiella Müll. Hal.', 'Avram Finnis', 'Hydrogen Peroxide', 64, 68, 145);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Leucas R. Br.', 'Jo-anne Ratley', 'Fluoxetine', 71, 76, 140);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Zahlbrucknerella fabispora Henssen', 'Giselle Balwin', 'Finasteride', 16, 21, 134);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Penstemon angustifolius Nutt. ex Pursh var. caudatus (A. Heller) Rydb.', 'Fayre Greveson', 'Burn with Aloe', 15, 20, 139);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Zanthoxylum coriaceum A. Rich.', 'Reina Murdoch', 'Acetaminophen and Codeine Phosphate', 43, 48, 145);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Aletris L.', 'Jojo Plenty', 'Clarithromycin', 77, 81, 132);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Stellaria alaskana Hultén', 'Zebedee Sinncock', 'Lisinopril and hydrochlorothiazide', 90, 93, 112);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Crotalaria cajanifolia Kunth', 'Penrod Petru', 'CLARINS Broad Spectrum SPF 30 Sunscreen For Face Wrinkle Control', 52, 57, 135);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Gmelina philippensis Cham.', 'Connie Rapinett', 'Pentazocine and naloxone', 76, 81, 100);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Muhlenbergia frondosa (Poir.) Fernald', 'Franciskus Tilt', 'FACE PROTECTOR', 59, 61, 139);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Taxiphyllum deplanatum (Bruch & Schimp. ex Sull.) Fleisch.', 'Marleah Worledge', 'Phenazopyridine', 27, 30, 107);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Neviusia A. Gray', 'Shay Iacovazzi', 'Ceramide Lift And Firm Makeup Broad Spectrum Sunscreen SPF 15 Toast', 35, 36, 115);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Rumex frutescens Thouars', 'Renell Arman', 'Rimmel London', 69, 70, 131);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Helenium amarum (Raf.) H. Rock var. amarum', 'Fedora Hoffman', 'Pink-Bismuth', 58, 63, 103);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Paspalum L.', 'Carole Elgey', 'Lidocaine Hydrochloride and Dextrose', 50, 51, 148);
insert into article (title, authors, keywords, pbegin, pend, "issueId") values ('Eriogonum racemosum Nutt.', 'Mari Willshere', 'Imipenem and Cilastatin', 95, 98, 135);

      `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
      queryRunner.query(``);
    }

}
